package com.liutaoyxz.rocketmq.mapper;

import com.liutaoyxz.rocketmq.entity.MqUser;
import com.liutaoyxz.rocketmq.entity.MqUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MqUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int countByExample(MqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int deleteByExample(MqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int insert(MqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int insertSelective(MqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    List<MqUser> selectByExample(MqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    MqUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MqUser record, @Param("example") MqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MqUser record, @Param("example") MqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqUser record);
}