package com.liutaoyxz.rocketmq.dao.mapper;

import com.liutaoyxz.rocketmq.dao.entity.MqCoupon;
import com.liutaoyxz.rocketmq.dao.entity.MqCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MqCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int countByExample(MqCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int deleteByExample(MqCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int insert(MqCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int insertSelective(MqCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    List<MqCoupon> selectByExample(MqCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    MqCoupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MqCoupon record, @Param("example") MqCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MqCoupon record, @Param("example") MqCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqCoupon record);
}