package com.liutaoyxz.rocketmq.dao.mapper;

import com.liutaoyxz.rocketmq.dao.entity.MqGoods;
import com.liutaoyxz.rocketmq.dao.entity.MqGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MqGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int countByExample(MqGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int deleteByExample(MqGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int insert(MqGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int insertSelective(MqGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    List<MqGoods> selectByExample(MqGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    MqGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MqGoods record, @Param("example") MqGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MqGoods record, @Param("example") MqGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqGoods record);
}