package com.liutaoyxz.rocketmq.dao.mapper;

import com.liutaoyxz.rocketmq.dao.entity.MqOrder;
import com.liutaoyxz.rocketmq.dao.entity.MqOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MqOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int countByExample(MqOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int deleteByExample(MqOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int insert(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int insertSelective(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    List<MqOrder> selectByExample(MqOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    MqOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MqOrder record, @Param("example") MqOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MqOrder record, @Param("example") MqOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqOrder record);
}