package com.liutaoyxz.rocketmq.dao.mapper;

import com.liutaoyxz.rocketmq.dao.entity.MqPay;
import com.liutaoyxz.rocketmq.dao.entity.MqPayExample;
import com.liutaoyxz.rocketmq.dao.entity.MqPayKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MqPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int countByExample(MqPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int deleteByExample(MqPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MqPayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int insert(MqPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int insertSelective(MqPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    List<MqPay> selectByExample(MqPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    MqPay selectByPrimaryKey(MqPayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MqPay record, @Param("example") MqPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MqPay record, @Param("example") MqPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqPay record);
}